batch_size: 2
# << gpu 메모리 
dset:
  test:
    data_dir: /home/ahnwooseob/mxfont/data/images/test  # path to reference images
    source_font: /home/ahnwooseob/mxfont/data/my_ttf/malgun.ttf   # path to .ttf file used as the source font during the generation
    gen_chars_file: /home/ahnwooseob/mxfont/kor_gen_test2.json   # path to file of the characters to generate. Leave blank if you want to generate all the available characters in the source font.
